apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest
      version: B
  template:
    metadata:
      labels:
        app: aceest
        version: B
    spec:
      containers:
        - name: aceest-container
          image: aceest-app:v2
          ports:
            - containerPort: 9000